---

- name: Add locales
  locale_gen: name="{{ item }}" state=present
  with_items:
  - fr_FR.UTF-8
  - en_US.UTF-8
  - en_GB.UTF-8
  tags:
  - locale

- name: Install default locale
  template:
    src:    etc_default_locale.j2
    dest:   /etc/default/locale
    mode:   0755
    owner:  root
    group:  root
  tags:
  - locale
